version: "3.7"
services:
  client-server:
    container_name: reports-server
    build: .
    restart: always
    depends_on:
      - mongo_db
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8087:8087"
  mongo_db:
    image: "mongo:5.0.1"
    restart: always
    ports:
      - "27022:27017"
networks:
  default:
    name: custom-network