server:
  port: '8087'

spring:
  profiles:
    active: @activatedProperties@
  application:
    name: reports

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: 'true'
    restart:
      enabled: 'true'

backend:
  service:
    account: 'http://account-service/accounts'
    credit: 'http://credits/credits'